# Generated by Django 3.2.7 on 2022-06-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('temat', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('tresc', models.TextField(max_length=255)),
            ],
        ),
    ]
