# Generated by Django 4.0.5 on 2023-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='czy_firma',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='email',
            field=models.EmailField(blank=True, default=False, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='imie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nazwisko',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
