# Generated by Django 4.0.5 on 2023-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_klient_czy_firma_alter_klient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
