# Generated by Django 4.0.5 on 2023-04-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_klient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='kod_pocztowy',
            field=models.CharField(max_length=50),
        ),
    ]
