# Generated by Django 4.0.5 on 2023-04-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_klient_kod_pocztowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='kraj',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='nazwa_firmy',
            field=models.CharField(max_length=150),
        ),
    ]
