# Generated by Django 4.0.5 on 2023-04-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_klient_kraj_alter_klient_nazwa_firmy'),
    ]

    operations = [
        migrations.AddField(
            model_name='serwisraport',
            name='zdjecia',
            field=models.FileField(blank=True, upload_to='zdjeciaraporty/'),
        ),
        migrations.AlterField(
            model_name='serwisraport',
            name='data_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='serwisraport',
            name='data_start',
            field=models.DateField(),
        ),
    ]
