# Generated by Django 4.0.5 on 2023-04-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_serwisraport_zdjecia_alter_serwisraport_data_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serwisraport',
            name='urzadzenia',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='serwisraport',
            name='zdjecia',
            field=models.FileField(blank=True, null=True, upload_to='zdjeciaraporty/'),
        ),
    ]
