# Generated by Django 4.0.5 on 2023-05-02 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0007_serwisraport_urzadzenia_alter_serwisraport_zdjecia'),
    ]

    operations = [
        migrations.AddField(
            model_name='serwisraport',
            name='pracownicy_szt',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='serwisraport',
            name='pracownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pracownik', to=settings.AUTH_USER_MODEL),
        ),
    ]
