# Generated by Django 4.0.5 on 2023-05-02 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0011_alter_serwisraport_pracownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serwisraport',
            name='pracownik',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
