# Generated by Django 4.0.5 on 2023-05-02 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0012_alter_serwisraport_pracownik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serwisraport',
            name='pracownik',
        ),
        migrations.AddField(
            model_name='serwisraport',
            name='pracownik',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
