# Generated by Django 4.0.5 on 2023-05-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_remove_serwisraport_pracownik_serwisraport_pracownik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serwisraport',
            name='data_start',
        ),
        migrations.AddField(
            model_name='serwisraport',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Nowe'), (2, 'Zafakturowane'), (3, 'Wysłane')], default=1, null=True),
        ),
    ]
