# Generated by Django 4.0.5 on 2023-05-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_remove_serwisraport_data_start_serwisraport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serwisraport',
            name='pracownik',
        ),
    ]
