# Generated by Django 4.0.5 on 2023-05-06 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0017_remove_serwisraport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serwisraport',
            name='pracownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serwisraport',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Nowe'), (2, 'Zafakturowane'), (3, 'Wysłane')], default=1, null=True),
        ),
    ]
