from .main_view import MainView
from .kontakt_view import KontaktView
from .alarmy_view import AlarmyView
from .polityka_view import PolitykaView
from .realizacje_view import RealizacjeView
from .certyfikaty_view import CertyfikatyView
from .monitoring_cctv_view import MonitoringCCTVView
from .sieci_view import SieciView
from .referencje_view import ReferencjeView
from .active_language import active_language
from .domofony_view import DomofonyView
from .elektryka_view import ElektrykaView
from .onas_view import ONasView
from .monitoring_gsm_view import MonitoringGSMView
from .videodomofony_view import VideoDomofonyView
from .kontrola_dostepu_view import KontrolaDostepuView
from .uslugi_serwisowe_view import UslugiSerwisoweView
