from .login_view import LoginView
from .forgot_view import ForgotView
from .dashboard_view import DashboardView
from .logout_view import LogoutView
from .addklient_view import AddKlientView
from .klientlist_view import KlientListView
from .addraport_view import AddRaportView
from .deleteklient import DeleteKlientView
from .editklient_view import EditKlientView
from .raportlist_view import RaportListView
from .raportdetail_view import RaportDetailView
from .raportdelete_view import DeleteRaportView
from .editraport_view import EditRaportView
from .raportfaktura_view import RaportFakturaView
from .generate_pfd_view import MyPDF
from .fakturywyslane_view import FakturyWyslaneView
from .fakturyzafakturowane_view import FakturyZafakturowaneView
from .gwarancja_view import GwarancjaView
from .raport_gwarancja import RaportGwarancjaView
from .nowe_raport_view import NoweRaportView
